### ISSUE TITLE
Code coverage?

### ISSUE THREAD

**Issue by ericis** [adriancarriger/clean-to-the-core#6]
What version of the CLI did you use to get code coverage?

I have:
> angular-cli: 1.0.0-beta.18
> node: 4.4.7
> os: win32 x64

**Comment by adriancarriger** [comment]
@ericis The last successful time coverage was sent to [Coveralls](https://coveralls.io/builds/8561189) was with commit 7b3a720 using angular-cli: 1.0.0-beta.18. 

Since then I've still been able to get coverage reports locally. After updating to angular-cli: 1.0.0-beta.19-3 you have to use `ng test --code-cover` to get coverage reports. Using the new command it's sending to Coveralls again, but it says "COVERAGE REMAINED THE SAME AT ?%" which seems related to lemurheavy/coveralls-public#854.

When it was working, I had to write a [small script](https://github.com/adriancarriger/clean-to-the-core/blob/master/scripts/fix_coverage.js#L19-L32) to remove some unnecessary text from the `coverage.lcov` file.

**Comment by ericis** [comment]
Thanks @adriancarriger!

I realized that my global version was different than my local project version and switched to "1.0.0-beta.19" per your readme by manually running `npm install angular-cli@1.0.0-beta.19-3 --save-dev` on the project. Now, I see the `--code-cover` option running correctly in my project.

This is great. Thanks for sharing your project too. I'm not using it directly, but it was an excellent reference for me.

**Comment by adriancarriger** [comment]
@ericis Awesome, glad it's helpful!
